### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by Rettich82** [AbdullahM0hamed/Aliucord-Plugins#3]
The plugin still works, but crashes by changeing the settings

**Comment by AbdullahM0hamed** [comment]
Could you elaborate on what you mean by "crashes by changing the settings" - it doesn't happen to me, and I'm not sure what settings it changes to cause a crash

Also, a crash log would be helpful if you could get that

**Comment by Rettich82** [comment]
![Screenshot_20211127-232728](https://user-images.githubusercontent.com/33241827/143722354-861f187f-42ff-4060-8e47-277a024c7c7d.jpg)

[2021-11-27_23_27_04.45.txt](https://github.com/AbdullahM0hamed/Aliucord-Plugins/files/7612469/2021-11-27_23_27_04.45.txt)

If I click the settings, the crash happens. Everytime I start the app, the error message appears. The plugin still works though

**Comment by AbdullahM0hamed** [comment]
[AvatarChanger.zip](https://github.com/AbdullahM0hamed/Aliucord-Plugins/files/7612592/AvatarChanger.zip)

Cannot test as I don't have the issue - but perhaps this works? Please let me know if it does/doesn't

**Comment by Rettich82** [comment]
Great. It works. No error message, no crash. Thank you!
